version: v1.1.0
alias: 
  values:
    repo: repo
secrets:
  - id: name
    keyvault: https://myacbvault2.vault.azure.net/secrets/SampleSecret
steps:
  - cmd: bash -c 'if [ -z "$MY_SECRET" ]; then echo "Secret not resolved"; else echo "Secret resolved"; fi'
    env: 
      - MY_SECRET='{{.Secrets.name}}' 

  # Login to Azure and list the tags to verify if we have the Image!
  - cmd: az login --identity
  - cmd: az acr repository show-tags -n {{.Values.registryName}} --repository repo
