name: Get Azure token
on:
  push:
    branches: [ main ]
    
permissions:
  id-token: write
  
jobs:
  Get-Azure-Token:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ../..
          CWD="$(pwd)"
          python3 -m venv oidc-venv
          . oidc-venv/bin/activate
          echo "activated environment"
          python3 -m pip install -q --upgrade pip
          echo "started installing cli beta" 
          pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
          echo "***************installed cli beta*******************"
          echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH
