name: Run Azure Login with OIDC
on: [push]

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 2717ed0e-ccde-4038-b033-d1c2204f0745
          tenant-id: 12e0baa0-471a-4a8b-afcf-dd2be7c58916
          allow-no-subscriptions: true
  
      - name: 'Run az commands'
        run: |
          token=$(az account get-access-token --resource=https://graph.microsoft.com | base64); echo $token
